# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import connector_sdk_pb2 as connector__sdk__pb2


class ConnectorStub(object):
    """Fivetran (grpc client) <> Connector (grpc server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigurationForm = channel.unary_unary(
                '/fivetran_sdk.Connector/ConfigurationForm',
                request_serializer=common__pb2.ConfigurationFormRequest.SerializeToString,
                response_deserializer=common__pb2.ConfigurationFormResponse.FromString,
                )
        self.Test = channel.unary_unary(
                '/fivetran_sdk.Connector/Test',
                request_serializer=common__pb2.TestRequest.SerializeToString,
                response_deserializer=common__pb2.TestResponse.FromString,
                )
        self.Schema = channel.unary_unary(
                '/fivetran_sdk.Connector/Schema',
                request_serializer=connector__sdk__pb2.SchemaRequest.SerializeToString,
                response_deserializer=connector__sdk__pb2.SchemaResponse.FromString,
                )
        self.Update = channel.unary_stream(
                '/fivetran_sdk.Connector/Update',
                request_serializer=connector__sdk__pb2.UpdateRequest.SerializeToString,
                response_deserializer=connector__sdk__pb2.UpdateResponse.FromString,
                )


class ConnectorServicer(object):
    """Fivetran (grpc client) <> Connector (grpc server)
    """

    def ConfigurationForm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Schema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigurationForm': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigurationForm,
                    request_deserializer=common__pb2.ConfigurationFormRequest.FromString,
                    response_serializer=common__pb2.ConfigurationFormResponse.SerializeToString,
            ),
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=common__pb2.TestRequest.FromString,
                    response_serializer=common__pb2.TestResponse.SerializeToString,
            ),
            'Schema': grpc.unary_unary_rpc_method_handler(
                    servicer.Schema,
                    request_deserializer=connector__sdk__pb2.SchemaRequest.FromString,
                    response_serializer=connector__sdk__pb2.SchemaResponse.SerializeToString,
            ),
            'Update': grpc.unary_stream_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=connector__sdk__pb2.UpdateRequest.FromString,
                    response_serializer=connector__sdk__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fivetran_sdk.Connector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connector(object):
    """Fivetran (grpc client) <> Connector (grpc server)
    """

    @staticmethod
    def ConfigurationForm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fivetran_sdk.Connector/ConfigurationForm',
            common__pb2.ConfigurationFormRequest.SerializeToString,
            common__pb2.ConfigurationFormResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fivetran_sdk.Connector/Test',
            common__pb2.TestRequest.SerializeToString,
            common__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Schema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fivetran_sdk.Connector/Schema',
            connector__sdk__pb2.SchemaRequest.SerializeToString,
            connector__sdk__pb2.SchemaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fivetran_sdk.Connector/Update',
            connector__sdk__pb2.UpdateRequest.SerializeToString,
            connector__sdk__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
