// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: common.proto

package fivetran_sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextField int32

const (
	TextField_PlainText TextField = 0
	TextField_Password  TextField = 1
	TextField_Hidden    TextField = 2
)

// Enum value maps for TextField.
var (
	TextField_name = map[int32]string{
		0: "PlainText",
		1: "Password",
		2: "Hidden",
	}
	TextField_value = map[string]int32{
		"PlainText": 0,
		"Password":  1,
		"Hidden":    2,
	}
)

func (x TextField) Enum() *TextField {
	p := new(TextField)
	*p = x
	return p
}

func (x TextField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextField) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (TextField) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x TextField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextField.Descriptor instead.
func (TextField) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type DataType int32

const (
	DataType_UNSPECIFIED    DataType = 0
	DataType_BOOLEAN        DataType = 1
	DataType_SHORT          DataType = 2
	DataType_INT            DataType = 3
	DataType_LONG           DataType = 4
	DataType_DECIMAL        DataType = 5
	DataType_FLOAT          DataType = 6
	DataType_DOUBLE         DataType = 7
	DataType_NAIVE_DATE     DataType = 8
	DataType_NAIVE_DATETIME DataType = 9
	DataType_UTC_DATETIME   DataType = 10
	DataType_BINARY         DataType = 11
	DataType_XML            DataType = 12
	DataType_STRING         DataType = 13
	DataType_JSON           DataType = 14
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "BOOLEAN",
		2:  "SHORT",
		3:  "INT",
		4:  "LONG",
		5:  "DECIMAL",
		6:  "FLOAT",
		7:  "DOUBLE",
		8:  "NAIVE_DATE",
		9:  "NAIVE_DATETIME",
		10: "UTC_DATETIME",
		11: "BINARY",
		12: "XML",
		13: "STRING",
		14: "JSON",
	}
	DataType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"BOOLEAN":        1,
		"SHORT":          2,
		"INT":            3,
		"LONG":           4,
		"DECIMAL":        5,
		"FLOAT":          6,
		"DOUBLE":         7,
		"NAIVE_DATE":     8,
		"NAIVE_DATETIME": 9,
		"UTC_DATETIME":   10,
		"BINARY":         11,
		"XML":            12,
		"STRING":         13,
		"JSON":           14,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type OpType int32

const (
	OpType_UPSERT   OpType = 0
	OpType_UPDATE   OpType = 1
	OpType_DELETE   OpType = 2
	OpType_TRUNCATE OpType = 3
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "UPSERT",
		1: "UPDATE",
		2: "DELETE",
		3: "TRUNCATE",
	}
	OpType_value = map[string]int32{
		"UPSERT":   0,
		"UPDATE":   1,
		"DELETE":   2,
		"TRUNCATE": 3,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type ConfigurationFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationFormRequest) Reset() {
	*x = ConfigurationFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationFormRequest) ProtoMessage() {}

func (x *ConfigurationFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationFormRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationFormRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type ConfigurationFormResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaSelectionSupported bool                 `protobuf:"varint,1,opt,name=schema_selection_supported,json=schemaSelectionSupported,proto3" json:"schema_selection_supported,omitempty"`
	TableSelectionSupported  bool                 `protobuf:"varint,2,opt,name=table_selection_supported,json=tableSelectionSupported,proto3" json:"table_selection_supported,omitempty"`
	Fields                   []*FormField         `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Tests                    []*ConfigurationTest `protobuf:"bytes,4,rep,name=tests,proto3" json:"tests,omitempty"`
}

func (x *ConfigurationFormResponse) Reset() {
	*x = ConfigurationFormResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationFormResponse) ProtoMessage() {}

func (x *ConfigurationFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationFormResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationFormResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigurationFormResponse) GetSchemaSelectionSupported() bool {
	if x != nil {
		return x.SchemaSelectionSupported
	}
	return false
}

func (x *ConfigurationFormResponse) GetTableSelectionSupported() bool {
	if x != nil {
		return x.TableSelectionSupported
	}
	return false
}

func (x *ConfigurationFormResponse) GetFields() []*FormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ConfigurationFormResponse) GetTests() []*ConfigurationTest {
	if x != nil {
		return x.Tests
	}
	return nil
}

type FormField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label       string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Required    bool    `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Types that are assignable to Type:
	//
	//	*FormField_TextField
	//	*FormField_DropdownField
	//	*FormField_ToggleField
	Type isFormField_Type `protobuf_oneof:"type"`
}

func (x *FormField) Reset() {
	*x = FormField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormField) ProtoMessage() {}

func (x *FormField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormField.ProtoReflect.Descriptor instead.
func (*FormField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *FormField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FormField) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (m *FormField) GetType() isFormField_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FormField) GetTextField() TextField {
	if x, ok := x.GetType().(*FormField_TextField); ok {
		return x.TextField
	}
	return TextField_PlainText
}

func (x *FormField) GetDropdownField() *DropdownField {
	if x, ok := x.GetType().(*FormField_DropdownField); ok {
		return x.DropdownField
	}
	return nil
}

func (x *FormField) GetToggleField() *ToggleField {
	if x, ok := x.GetType().(*FormField_ToggleField); ok {
		return x.ToggleField
	}
	return nil
}

type isFormField_Type interface {
	isFormField_Type()
}

type FormField_TextField struct {
	TextField TextField `protobuf:"varint,5,opt,name=text_field,json=textField,proto3,enum=fivetran_sdk.TextField,oneof"`
}

type FormField_DropdownField struct {
	DropdownField *DropdownField `protobuf:"bytes,6,opt,name=dropdown_field,json=dropdownField,proto3,oneof"`
}

type FormField_ToggleField struct {
	ToggleField *ToggleField `protobuf:"bytes,7,opt,name=toggle_field,json=toggleField,proto3,oneof"`
}

func (*FormField_TextField) isFormField_Type() {}

func (*FormField_DropdownField) isFormField_Type() {}

func (*FormField_ToggleField) isFormField_Type() {}

type DropdownField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DropdownField []string `protobuf:"bytes,1,rep,name=dropdown_field,json=dropdownField,proto3" json:"dropdown_field,omitempty"`
}

func (x *DropdownField) Reset() {
	*x = DropdownField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropdownField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropdownField) ProtoMessage() {}

func (x *DropdownField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropdownField.ProtoReflect.Descriptor instead.
func (*DropdownField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *DropdownField) GetDropdownField() []string {
	if x != nil {
		return x.DropdownField
	}
	return nil
}

type ToggleField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToggleField) Reset() {
	*x = ToggleField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleField) ProtoMessage() {}

func (x *ToggleField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleField.ProtoReflect.Descriptor instead.
func (*ToggleField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type ConfigurationTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // unique identifier for the test
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // A few words indicating what we are testing, e.g. 'Connecting to database'
}

func (x *ConfigurationTest) Reset() {
	*x = ConfigurationTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationTest) ProtoMessage() {}

func (x *ConfigurationTest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationTest.ProtoReflect.Descriptor instead.
func (*ConfigurationTest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigurationTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationTest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type TestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Configuration map[string]string `protobuf:"bytes,2,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *TestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestRequest) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type TestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*TestResponse_Success
	//	*TestResponse_Failure
	Response isTestResponse_Response `protobuf_oneof:"response"`
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (m *TestResponse) GetResponse() isTestResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TestResponse) GetSuccess() bool {
	if x, ok := x.GetResponse().(*TestResponse_Success); ok {
		return x.Success
	}
	return false
}

func (x *TestResponse) GetFailure() string {
	if x, ok := x.GetResponse().(*TestResponse_Failure); ok {
		return x.Failure
	}
	return ""
}

type isTestResponse_Response interface {
	isTestResponse_Response()
}

type TestResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3,oneof"`
}

type TestResponse_Failure struct {
	Failure string `protobuf:"bytes,2,opt,name=failure,proto3,oneof"` // potential future warning
}

func (*TestResponse_Success) isTestResponse_Response() {}

func (*TestResponse_Failure) isTestResponse_Response() {}

type SchemaList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schemas []*Schema `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
}

func (x *SchemaList) Reset() {
	*x = SchemaList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaList) ProtoMessage() {}

func (x *SchemaList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaList.ProtoReflect.Descriptor instead.
func (*SchemaList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *SchemaList) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type TableList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tables []*Table `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
}

func (x *TableList) Reset() {
	*x = TableList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableList) ProtoMessage() {}

func (x *TableList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableList.ProtoReflect.Descriptor instead.
func (*TableList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *TableList) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tables []*Table `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type DecimalParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Precision uint32 `protobuf:"varint,1,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale     uint32 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *DecimalParams) Reset() {
	*x = DecimalParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecimalParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalParams) ProtoMessage() {}

func (x *DecimalParams) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalParams.ProtoReflect.Descriptor instead.
func (*DecimalParams) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *DecimalParams) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *DecimalParams) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type ValueType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Inner:
	//
	//	*ValueType_Null
	//	*ValueType_Bool
	//	*ValueType_Short
	//	*ValueType_Int
	//	*ValueType_Long
	//	*ValueType_Float
	//	*ValueType_Double
	//	*ValueType_NaiveDate
	//	*ValueType_NaiveDatetime
	//	*ValueType_UtcDatetime
	//	*ValueType_Decimal
	//	*ValueType_Binary
	//	*ValueType_String_
	//	*ValueType_Json
	//	*ValueType_Xml
	Inner isValueType_Inner `protobuf_oneof:"inner"`
}

func (x *ValueType) Reset() {
	*x = ValueType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType.ProtoReflect.Descriptor instead.
func (*ValueType) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (m *ValueType) GetInner() isValueType_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (x *ValueType) GetNull() bool {
	if x, ok := x.GetInner().(*ValueType_Null); ok {
		return x.Null
	}
	return false
}

func (x *ValueType) GetBool() bool {
	if x, ok := x.GetInner().(*ValueType_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *ValueType) GetShort() int32 {
	if x, ok := x.GetInner().(*ValueType_Short); ok {
		return x.Short
	}
	return 0
}

func (x *ValueType) GetInt() int32 {
	if x, ok := x.GetInner().(*ValueType_Int); ok {
		return x.Int
	}
	return 0
}

func (x *ValueType) GetLong() int64 {
	if x, ok := x.GetInner().(*ValueType_Long); ok {
		return x.Long
	}
	return 0
}

func (x *ValueType) GetFloat() float32 {
	if x, ok := x.GetInner().(*ValueType_Float); ok {
		return x.Float
	}
	return 0
}

func (x *ValueType) GetDouble() float64 {
	if x, ok := x.GetInner().(*ValueType_Double); ok {
		return x.Double
	}
	return 0
}

func (x *ValueType) GetNaiveDate() *timestamppb.Timestamp {
	if x, ok := x.GetInner().(*ValueType_NaiveDate); ok {
		return x.NaiveDate
	}
	return nil
}

func (x *ValueType) GetNaiveDatetime() *timestamppb.Timestamp {
	if x, ok := x.GetInner().(*ValueType_NaiveDatetime); ok {
		return x.NaiveDatetime
	}
	return nil
}

func (x *ValueType) GetUtcDatetime() *timestamppb.Timestamp {
	if x, ok := x.GetInner().(*ValueType_UtcDatetime); ok {
		return x.UtcDatetime
	}
	return nil
}

func (x *ValueType) GetDecimal() string {
	if x, ok := x.GetInner().(*ValueType_Decimal); ok {
		return x.Decimal
	}
	return ""
}

func (x *ValueType) GetBinary() []byte {
	if x, ok := x.GetInner().(*ValueType_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *ValueType) GetString_() string {
	if x, ok := x.GetInner().(*ValueType_String_); ok {
		return x.String_
	}
	return ""
}

func (x *ValueType) GetJson() string {
	if x, ok := x.GetInner().(*ValueType_Json); ok {
		return x.Json
	}
	return ""
}

func (x *ValueType) GetXml() string {
	if x, ok := x.GetInner().(*ValueType_Xml); ok {
		return x.Xml
	}
	return ""
}

type isValueType_Inner interface {
	isValueType_Inner()
}

type ValueType_Null struct {
	Null bool `protobuf:"varint,1,opt,name=null,proto3,oneof"`
}

type ValueType_Bool struct {
	Bool bool `protobuf:"varint,2,opt,name=bool,proto3,oneof"`
}

type ValueType_Short struct {
	Short int32 `protobuf:"varint,3,opt,name=short,proto3,oneof"`
}

type ValueType_Int struct {
	Int int32 `protobuf:"varint,4,opt,name=int,proto3,oneof"`
}

type ValueType_Long struct {
	Long int64 `protobuf:"varint,5,opt,name=long,proto3,oneof"`
}

type ValueType_Float struct {
	Float float32 `protobuf:"fixed32,6,opt,name=float,proto3,oneof"`
}

type ValueType_Double struct {
	Double float64 `protobuf:"fixed64,7,opt,name=double,proto3,oneof"`
}

type ValueType_NaiveDate struct {
	NaiveDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=naive_date,json=naiveDate,proto3,oneof"`
}

type ValueType_NaiveDatetime struct {
	NaiveDatetime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=naive_datetime,json=naiveDatetime,proto3,oneof"`
}

type ValueType_UtcDatetime struct {
	UtcDatetime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=utc_datetime,json=utcDatetime,proto3,oneof"`
}

type ValueType_Decimal struct {
	Decimal string `protobuf:"bytes,11,opt,name=decimal,proto3,oneof"`
}

type ValueType_Binary struct {
	Binary []byte `protobuf:"bytes,12,opt,name=binary,proto3,oneof"`
}

type ValueType_String_ struct {
	String_ string `protobuf:"bytes,13,opt,name=string,proto3,oneof"`
}

type ValueType_Json struct {
	Json string `protobuf:"bytes,14,opt,name=json,proto3,oneof"`
}

type ValueType_Xml struct {
	Xml string `protobuf:"bytes,15,opt,name=xml,proto3,oneof"`
}

func (*ValueType_Null) isValueType_Inner() {}

func (*ValueType_Bool) isValueType_Inner() {}

func (*ValueType_Short) isValueType_Inner() {}

func (*ValueType_Int) isValueType_Inner() {}

func (*ValueType_Long) isValueType_Inner() {}

func (*ValueType_Float) isValueType_Inner() {}

func (*ValueType_Double) isValueType_Inner() {}

func (*ValueType_NaiveDate) isValueType_Inner() {}

func (*ValueType_NaiveDatetime) isValueType_Inner() {}

func (*ValueType_UtcDatetime) isValueType_Inner() {}

func (*ValueType_Decimal) isValueType_Inner() {}

func (*ValueType_Binary) isValueType_Inner() {}

func (*ValueType_String_) isValueType_Inner() {}

func (*ValueType_Json) isValueType_Inner() {}

func (*ValueType_Xml) isValueType_Inner() {}

type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns []*Column `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       DataType       `protobuf:"varint,2,opt,name=type,proto3,enum=fivetran_sdk.DataType" json:"type,omitempty"`
	PrimaryKey bool           `protobuf:"varint,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Decimal    *DecimalParams `protobuf:"bytes,4,opt,name=decimal,proto3,oneof" json:"decimal,omitempty"`
}

func (x *Column) Reset() {
	*x = Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_UNSPECIFIED
}

func (x *Column) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Column) GetDecimal() *DecimalParams {
	if x != nil {
		return x.Decimal
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a,
	0x18, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f,
	0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x19, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x1a, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x18, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x3a, 0x0a, 0x19, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x12, 0x35, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x22, 0xd0, 0x02, 0x0a, 0x09, 0x46, 0x6f,
	0x72, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x25, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74,
	0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x48, 0x00, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x44,
	0x0a, 0x0e, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61,
	0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x69, 0x76,
	0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0d,
	0x44, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x72, 0x6f, 0x70, 0x64, 0x6f, 0x77, 0x6e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x22, 0xb7, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x40, 0x0a, 0x12, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x52, 0x0a, 0x0c,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x3c, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x07, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x07, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x22, 0x38,
	0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69,
	0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61,
	0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x06, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0xf1, 0x03, 0x0a, 0x09, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x04,
	0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f,
	0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x06,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x6e, 0x61, 0x69, 0x76, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x61, 0x69, 0x76, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x6e, 0x61, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x61, 0x69, 0x76, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x75, 0x74, 0x63, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x74,
	0x63, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12,
	0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03,
	0x78, 0x6d, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x05,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x69, 0x76,
	0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x06, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61,
	0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61,
	0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x88, 0x01,
	0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x2a, 0x34, 0x0a,
	0x09, 0x54, 0x65, 0x78, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x6c,
	0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x69, 0x64, 0x64, 0x65,
	0x6e, 0x10, 0x02, 0x2a, 0xcb, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x53, 0x48, 0x4f, 0x52, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f,
	0x41, 0x54, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x07,
	0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x41, 0x49, 0x56, 0x45, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10, 0x08,
	0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x41, 0x49, 0x56, 0x45, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x54, 0x49,
	0x4d, 0x45, 0x10, 0x09, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x54, 0x43, 0x5f, 0x44, 0x41, 0x54, 0x45,
	0x54, 0x49, 0x4d, 0x45, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59,
	0x10, 0x0b, 0x12, 0x07, 0x0a, 0x03, 0x58, 0x4d, 0x4c, 0x10, 0x0c, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10,
	0x0e, 0x2a, 0x3a, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x50, 0x53, 0x45, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x54, 0x52, 0x55, 0x4e, 0x43, 0x41, 0x54, 0x45, 0x10, 0x03, 0x42, 0x1f, 0x48,
	0x01, 0x50, 0x01, 0x5a, 0x19, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x69, 0x76, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x73, 0x64, 0x6b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_common_proto_goTypes = []interface{}{
	(TextField)(0),                    // 0: fivetran_sdk.TextField
	(DataType)(0),                     // 1: fivetran_sdk.DataType
	(OpType)(0),                       // 2: fivetran_sdk.OpType
	(*ConfigurationFormRequest)(nil),  // 3: fivetran_sdk.ConfigurationFormRequest
	(*ConfigurationFormResponse)(nil), // 4: fivetran_sdk.ConfigurationFormResponse
	(*FormField)(nil),                 // 5: fivetran_sdk.FormField
	(*DropdownField)(nil),             // 6: fivetran_sdk.DropdownField
	(*ToggleField)(nil),               // 7: fivetran_sdk.ToggleField
	(*ConfigurationTest)(nil),         // 8: fivetran_sdk.ConfigurationTest
	(*TestRequest)(nil),               // 9: fivetran_sdk.TestRequest
	(*TestResponse)(nil),              // 10: fivetran_sdk.TestResponse
	(*SchemaList)(nil),                // 11: fivetran_sdk.SchemaList
	(*TableList)(nil),                 // 12: fivetran_sdk.TableList
	(*Schema)(nil),                    // 13: fivetran_sdk.Schema
	(*DecimalParams)(nil),             // 14: fivetran_sdk.DecimalParams
	(*ValueType)(nil),                 // 15: fivetran_sdk.ValueType
	(*Table)(nil),                     // 16: fivetran_sdk.Table
	(*Column)(nil),                    // 17: fivetran_sdk.Column
	nil,                               // 18: fivetran_sdk.TestRequest.ConfigurationEntry
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	5,  // 0: fivetran_sdk.ConfigurationFormResponse.fields:type_name -> fivetran_sdk.FormField
	8,  // 1: fivetran_sdk.ConfigurationFormResponse.tests:type_name -> fivetran_sdk.ConfigurationTest
	0,  // 2: fivetran_sdk.FormField.text_field:type_name -> fivetran_sdk.TextField
	6,  // 3: fivetran_sdk.FormField.dropdown_field:type_name -> fivetran_sdk.DropdownField
	7,  // 4: fivetran_sdk.FormField.toggle_field:type_name -> fivetran_sdk.ToggleField
	18, // 5: fivetran_sdk.TestRequest.configuration:type_name -> fivetran_sdk.TestRequest.ConfigurationEntry
	13, // 6: fivetran_sdk.SchemaList.schemas:type_name -> fivetran_sdk.Schema
	16, // 7: fivetran_sdk.TableList.tables:type_name -> fivetran_sdk.Table
	16, // 8: fivetran_sdk.Schema.tables:type_name -> fivetran_sdk.Table
	19, // 9: fivetran_sdk.ValueType.naive_date:type_name -> google.protobuf.Timestamp
	19, // 10: fivetran_sdk.ValueType.naive_datetime:type_name -> google.protobuf.Timestamp
	19, // 11: fivetran_sdk.ValueType.utc_datetime:type_name -> google.protobuf.Timestamp
	17, // 12: fivetran_sdk.Table.columns:type_name -> fivetran_sdk.Column
	1,  // 13: fivetran_sdk.Column.type:type_name -> fivetran_sdk.DataType
	14, // 14: fivetran_sdk.Column.decimal:type_name -> fivetran_sdk.DecimalParams
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationFormResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropdownField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchemaList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecimalParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*FormField_TextField)(nil),
		(*FormField_DropdownField)(nil),
		(*FormField_ToggleField)(nil),
	}
	file_common_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*TestResponse_Success)(nil),
		(*TestResponse_Failure)(nil),
	}
	file_common_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ValueType_Null)(nil),
		(*ValueType_Bool)(nil),
		(*ValueType_Short)(nil),
		(*ValueType_Int)(nil),
		(*ValueType_Long)(nil),
		(*ValueType_Float)(nil),
		(*ValueType_Double)(nil),
		(*ValueType_NaiveDate)(nil),
		(*ValueType_NaiveDatetime)(nil),
		(*ValueType_UtcDatetime)(nil),
		(*ValueType_Decimal)(nil),
		(*ValueType_Binary)(nil),
		(*ValueType_String_)(nil),
		(*ValueType_Json)(nil),
		(*ValueType_Xml)(nil),
	}
	file_common_proto_msgTypes[14].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
