FROM azul/zulu-openjdk-alpine:21.0.1-21.30.15

COPY run_sdk_connector_tester_deploy.jar /app/SdkConnectorTester.jar

# /data folder will get mapped externally when the image is run

EXPOSE 50051

ENTRYPOINT ["java", "-jar", "/app/SdkConnectorTester.jar", "--working-dir=/data"]
